# Generated by Django 4.2.1 on 2023-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='wordcount',
            field=models.CharField(default='ok', max_length=15),
        ),
    ]
